from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import JSONResponse, Response
import numpy as np

from app.gps_schemas import GpsSimulationRequest, GpsSimulationResponse, IQFormat
from app.gps_engine import GpsEngine

router = APIRouter(tags=["GPS SDR Signal Simulator"])

@router.post("/simulate", response_model=GpsSimulationResponse)
def simulate_gps_signal(req: GpsSimulationRequest):
    """
    Simulate GPS L1 C/A SDR Baseband Constellation Signal (gps-sdr-sim).
    Computes satellite positions, Doppler shifts, C/N0, DOP, and synthesizes I/Q baseband samples.
    """
    try:
        res = GpsEngine.simulate(
            lat_deg=req.latitude_deg,
            lon_deg=req.longitude_deg,
            alt_m=req.altitude_m,
            elevation_mask_deg=req.elevation_mask_deg,
            sample_rate_hz=req.sample_rate_hz,
            duration_s=req.duration_s,
            iq_format=req.iq_format.value
        )
        return res
    except ValueError as ve:
        raise HTTPException(status_code=422, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GPS_SIMULATION_ERROR: {str(e)}")

@router.get("/gold-code/{prn}")
def get_gold_code(prn: int):
    """
    Generates the exact 1023-chip GPS C/A Gold Code sequence and auto-correlation function for PRN 1..32.
    """
    if prn < 1 or prn > 32:
        raise HTTPException(status_code=400, detail="PRN must be between 1 and 32")

    code = GpsEngine.generate_gold_code(prn)
    corr = GpsEngine.compute_auto_correlation(code)

    return {
        "prn": prn,
        "chip_length": len(code),
        "code_chips": code.tolist(),
        "auto_correlation": corr.tolist(),
        "g2_taps": GpsEngine.PRN_TAPS[prn]
    }

@router.post("/export-iq-bin")
def export_iq_binary(req: GpsSimulationRequest):
    """
    Export binary I/Q file compatible with HackRF One (int8), USRP (int16), or RTL-SDR (uint8)
    as generated by gps-sdr-sim.
    """
    try:
        res = GpsEngine.simulate(
            lat_deg=req.latitude_deg,
            lon_deg=req.longitude_deg,
            alt_m=req.altitude_m,
            elevation_mask_deg=req.elevation_mask_deg,
            sample_rate_hz=req.sample_rate_hz,
            duration_s=req.duration_s,
            iq_format=req.iq_format.value
        )

        i_data = np.array(res["iq_data_preview_i"], dtype=float)
        q_data = np.array(res["iq_data_preview_q"], dtype=float)

        if req.iq_format == IQFormat.INT8:
            # HackRF 8-bit signed IQ
            i_quant = np.clip(i_data * 127.0, -128, 127).astype(np.int8)
            q_quant = np.clip(q_data * 127.0, -128, 127).astype(np.int8)
            interleaved = np.empty((len(i_data) * 2,), dtype=np.int8)
            interleaved[0::2] = i_quant
            interleaved[1::2] = q_quant
            filename = f"gps_sim_{req.sample_rate_hz}hz_int8.bin"
        elif req.iq_format == IQFormat.INT16:
            # USRP 16-bit signed IQ
            i_quant = np.clip(i_data * 32767.0, -32768, 32767).astype(np.int16)
            q_quant = np.clip(q_data * 32767.0, -32768, 32767).astype(np.int16)
            interleaved = np.empty((len(i_data) * 2,), dtype=np.int16)
            interleaved[0::2] = i_quant
            interleaved[1::2] = q_quant
            filename = f"gps_sim_{req.sample_rate_hz}hz_int16.bin"
        else:
            # RTL-SDR 8-bit unsigned IQ
            i_quant = np.clip((i_data + 1.0) * 127.5, 0, 255).astype(np.uint8)
            q_quant = np.clip((q_data + 1.0) * 127.5, 0, 255).astype(np.uint8)
            interleaved = np.empty((len(i_data) * 2,), dtype=np.uint8)
            interleaved[0::2] = i_quant
            interleaved[1::2] = q_quant
            filename = f"gps_sim_{req.sample_rate_hz}hz_uint8.bin"

        return Response(
            content=bytes(interleaved.tobytes()),
            media_type="application/octet-stream",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
