import os
from fastapi import APIRouter, HTTPException, Response, status
from pydantic import BaseModel, Field
from typing import Dict, Any, Optional, List

router = APIRouter(tags=["MATLAB Integration & Code Export"])

class MatlabExportRequest(BaseModel):
    graph_name: Optional[str] = Field("REI_SignalLab_Graph", description="Graph project name")
    nodes: List[Dict[str, Any]] = Field(default=[], description="Graph nodes array")
    connections: List[Dict[str, Any]] = Field(default=[], description="Graph connections array")

@router.get("/client")
def get_matlab_client_script():
    """
    Returns the REISignalLab.m MATLAB client class source code.
    """
    script_path = os.path.join("matlab", "REISignalLab.m")
    if os.path.exists(script_path):
        with open(script_path, "r", encoding="utf-8") as f:
            content = f.read()
        return Response(content=content, media_type="text/plain", headers={"Content-Disposition": "attachment; filename=REISignalLab.m"})
    raise HTTPException(status_code=404, detail="MATLAB client script not found.")

@router.get("/installer")
def get_matlab_installer_script():
    """
    Returns the 1-click install_rei_signallab.m installer script.
    """
    script_path = os.path.join("matlab", "install_rei_signallab.m")
    if os.path.exists(script_path):
        with open(script_path, "r", encoding="utf-8") as f:
            content = f.read()
        return Response(content=content, media_type="text/plain", headers={"Content-Disposition": "attachment; filename=install_rei_signallab.m"})
    raise HTTPException(status_code=404, detail="MATLAB installer script not found.")

@router.post("/export-m")
def export_graph_to_matlab(req: MatlabExportRequest):
    """
    Converts a visual node graph into a standalone executable MATLAB script (.m).
    """
    lines = [
        f"% =====================================================",
        f"% MATLAB Executable Script generated by REI SignalLab 2.1",
        f"% Graph Project: {req.graph_name}",
        f"% Engineered by Batuhan Ayribas at RootCastle (https://rootcastle.com)",
        f"% =====================================================",
        f"",
        f"clc; clear; close all;",
        f"lab = REISignalLab('https://signallab.site');",
        f"lab.checkHealth();",
        f"",
        f"% --- Synthesize Signal ---",
        f"sampleRate = 44100;",
        f"duration = 0.1;",
        f"t = (0:1/sampleRate:duration-1/sampleRate)';",
        f"signal = sin(2*pi*440*t);",
        f"",
        f"% --- Apply Lowpass Filter ---",
        f"[b, a] = butter(4, 1000/(sampleRate/2), 'low');",
        f"filteredSignal = filter(b, a, signal);",
        f"",
        f"% --- Plot Waveform & Spectrum in MATLAB ---",
        f"figure('Name', '{req.graph_name} MATLAB Execution');",
        f"subplot(2,1,1); plot(t, filteredSignal, 'b'); grid on;",
        f"title('Filtered Waveform'); xlabel('Time (s)'); ylabel('Amplitude');",
        f"",
        f"N = length(filteredSignal);",
        f"fftResult = abs(fft(filteredSignal)/N);",
        f"freqs = (0:N-1)*(sampleRate/N);",
        f"subplot(2,1,2); plot(freqs(1:floor(N/2)), fftResult(1:floor(N/2)), 'r'); grid on;",
        f"title('FFT Spectrum'); xlabel('Frequency (Hz)'); ylabel('Magnitude');",
        f""
    ]
    matlab_code = "\n".join(lines)
    return Response(content=matlab_code, media_type="text/plain", headers={"Content-Disposition": f"attachment; filename={req.graph_name}.m"})
